server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webmvc:
          cors:
            mappings:
              '[/**]':
                allowed-origins: "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"

          routes:
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/