apiVersion: apps/v1
kind: Deployment

metadata:
  name: service-registry

spec:
  replicas: 1

  selector:
    matchLabels:
      app: service-registry

  template:
    metadata:
      labels:
        app: service-registry

    spec:
      containers:
        - name: service-registry
          image: saketkrishna18/service-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761